version: '1.0'

clustering:
  algorithm: dbscan
  enabled: false
  eps: 0.7
  min_samples: 3

# Not used yet
processing:
  clutter_removal: false
  frame_period_ms: 200.0
  mob_enabled: false
  mob_threshold: 0.5

# Not used yet
radar:
  doppler_resolution: 0.1
  max_range: 10.0
  max_velocity: 5.0
  num_doppler_bins: 16.0
  num_range_bins: 256
  range_idx_to_meters: 0.1
  range_resolution: 0.1

tracking:
  dt: 0.2
  enabled: false
  max_distance: 3.5
  max_misses: 5
  min_hits: 3

display:
  plot_height: 600
  plot_width: 1100
  update_period_ms: 10
  x_range:
  - -2.5
  - 2.5
  y_range:
  - 0.0
  - 8.0

# record command
recording:
  enabled: true
  formats:
    - csv
#    - pcd
  prefix: radar_data
  directory: recordings
  buffer_in_memory: false
