xwr68xx/mmw/dss/dss_main.c File Reference
dss_main.c File Reference
This is the main file which implements the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/sysbios/family/c64p/Hwi.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/control/dpm/dpm.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/datapath/dpc/objectdetection/objdetdsp/objectdetection.h>
#include <ti/demo/xwr68xx/mmw/include/mmw_output.h>
#include <ti/demo/xwr68xx/mmw/dss/mmw_dss.h>
#include <ti/demo/xwr68xx/mmw/mmw_res.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
Macros
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 5
Task Priority settings:
#define MMWDEMO_OBJDET_L2RAM_SIZE (49U * 1024U)
#define MMWDEMO_OBJDET_L1RAM_SIZE (16U * 1024U)
#define DPC_OBJDET_DSP_INSTANCEID (0xDEEDDEED)
Functions
static void MmwDemo_dssInitTask (UArg arg0, UArg arg1)
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1)
static void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx)
static void MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn (uint8_t subFrameIndx)
static void MmwDemo_updateObjectDetStats (DPC_ObjectDetection_Stats *currDpcStats, MmwDemo_output_message_stats *outputMsgStats)
static int32_t MmwDemo_copyResultToHSRAM (MmwDemo_HSRAM *ptrHsramBuffer, DPC_ObjectDetection_ExecuteResult *result, MmwDemo_output_message_stats *outStats)
static void MmwDemo_DPC_ObjectDetection_dpmTask (UArg arg0, UArg arg1)
static void MmwDemo_sensorStopEpilog (void)
void MmwDemo_edmaInit (MmwDemo_DataPathObj *obj, uint8_t instance)
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj *obj, uint8_t instance)
void MmwDemo_edmaClose (MmwDemo_DataPathObj *obj)
void MmwDemo_sleep (void)
int main (void)
Variables
uint8_t gMmwL3 [SOC_L3RAM_SIZE]
uint8_t gDPC_ObjDetL2Heap [MMWDEMO_OBJDET_L2RAM_SIZE]
uint8_t gDPC_ObjDetL1Heap [MMWDEMO_OBJDET_L1RAM_SIZE]
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
DPM_Buffer resultBuffer
Global Variable for DPM result buffer.
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
Detailed Description
This is the main file which implements the millimeter wave Demo.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dss_main.c.
Macro Definition Documentation
DPC_OBJDET_DSP_INSTANCEID
#define DPC_OBJDET_DSP_INSTANCEID (0xDEEDDEED)
HSRAM for processing results
Definition at line 113 of file dss_main.c.
MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 5
Task Priority settings:
Definition at line 93 of file dss_main.c.
MMWDEMO_OBJDET_L1RAM_SIZE
#define MMWDEMO_OBJDET_L1RAM_SIZE (16U * 1024U)
L1 RAM buffer for object detection DPC
Definition at line 105 of file dss_main.c.
MMWDEMO_OBJDET_L2RAM_SIZE
#define MMWDEMO_OBJDET_L2RAM_SIZE (49U * 1024U)
L2 RAM buffer for object detection DPC
Definition at line 100 of file dss_main.c.
Function Documentation
main()
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 845 of file dss_main.c.
References gMmwDssMCB, MmwDemo_DSS_MCB_t::initTaskHandle, MmwDemo_debugAssert, MmwDemo_dssInitTask(), and MmwDemo_DSS_MCB_t::socHandle.
MmwDemo_copyResultToHSRAM()
static int32_t MmwDemo_copyResultToHSRAM (MmwDemo_HSRAM * ptrHsramBuffer, DPC_ObjectDetection_ExecuteResult * result, MmwDemo_output_message_stats * outStats) static
Description
Copy DPC results and output stats to HSRAM to share with MSS
Parameters
[in] ptrHsramBuffer Pointer to HSRAM buffer memory
[in] result Pointer to DPC results
[in] outStats Pointer to Output message stats
Return values
Not Applicable.
Definition at line 537 of file dss_main.c.
References MMWDEMO_HSRAM_PAYLOAD_SIZE, DPC_ObjectDetection_ExecuteResult_t::objOut, MmwDemo_HSRAM_t::outStats, MmwDemo_HSRAM_t::payload, and MmwDemo_HSRAM_t::result.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
MmwDemo_DPC_ObjectDetection_dpmTask()
static void MmwDemo_DPC_ObjectDetection_dpmTask (UArg arg0, UArg arg1) static
Description
DPM Execution Task. DPM execute results are processed here: a) Update states based on timestamp from DPC. b) Copy results to shared memory to be shared with MSS. c) Send Results to MSS by calling DPM_sendResult()
Return values
Not Applicable.
Definition at line 659 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathObj, DPM_execute(), DPM_sendResult(), gHSRAM, gMmwDssMCB, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_copyResultToHSRAM(), MmwDemo_debugAssert, MmwDemo_updateObjectDetStats(), MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_HSRAM_t::outStats, DPM_Buffer_t::ptrBuffer, MmwDemo_HSRAM_t::result, resultBuffer, DPM_Buffer_t::size, DPC_ObjectDetection_ExecuteResult_t::stats, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, and MmwDemo_DataPathObj_t::subFrameStats.
Referenced by MmwDemo_dssInitTask().
MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn()
static void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx) static
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of frame/sub-frame processing. Note: In this demo objdetdsp DPC only have inter-frame processing, hence this callback function won't be called.
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 468 of file dss_main.c.
Referenced by MmwDemo_dssInitTask().
MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn()
static void MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn (uint8_t subFrameIndx) static
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of inter-frame/inter-sub-frame processing, we use this to issue BIOS calls for computing CPU load during active frame (chirping)
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 485 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathObj, gMmwDssMCB, MmwDemo_output_message_stats_t::interFrameCPULoad, and MmwDemo_DataPathObj_t::subFrameStats.
Referenced by MmwDemo_dssInitTask().
MmwDemo_DPC_ObjectDetection_reportFxn()
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1) static
Description
DPM Registered Report Handler. The DPM Module uses this registered function to notify the application about DPM reports.
Parameters
[in] reportType Report Type
[in] instanceId Instance Identifier which generated the report
[in] errCode Error code if any.
[in] arg0 Argument 0 interpreted with the report type
[in] arg1 Argument 1 interpreted with the report type
Return values
Not Applicable.
Definition at line 347 of file dss_main.c.
References DPM_Report_DPC_ASSERT, DPM_Report_DPC_INFO, DPM_Report_DPC_STARTED, DPM_Report_DPC_STOPPED, DPM_Report_IOCTL, DPM_Report_NOTIFY_DPC_RESULT, DPM_Report_NOTIFY_DPC_RESULT_ACKED, MmwDemo_DSS_MCB_t::dpmStartEvents, MmwDemo_DSS_MCB_t::dpmStopEvents, DPM_DPCAssert_t::fileName, gMmwDssMCB, DPM_DPCAssert_t::lineNum, and MmwDemo_sensorStopEpilog().
Referenced by MmwDemo_dssInitTask().
MmwDemo_dssInitTask()
static void MmwDemo_dssInitTask (UArg arg0, UArg arg1) static
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 723 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathObj, DPC_OBJDET_DSP_EDMA_INSTANCE, DPC_OBJDET_DSP_INSTANCEID, DPM_Domain_DISTRIBUTED, DPM_init(), DPM_synch(), MmwDemo_DataPathObj_t::edmaHandle, gDPC_ObjDetL1Heap, gDPC_ObjDetL2Heap, gDPC_ObjectDetectionCfg, gMmwDssMCB, gMmwL3, MmwDemo_debugAssert, MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY, MmwDemo_DPC_ObjectDetection_dpmTask(), MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_edmaInit(), MmwDemo_edmaOpen(), MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_DSS_MCB_t::objDetDpmTaskHandle, and MmwDemo_DSS_MCB_t::socHandle.
Referenced by main().
MmwDemo_EDMA_errorCallbackFxn()
static void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo)
Description
Call back function for EDMA CC (Channel controller) error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 202 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_errorInfo, gMmwDssMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
MmwDemo_EDMA_transferControllerErrorCallbackFxn()
static void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo)
Description
Call back function for EDMA transfer controller error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 215 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, gMmwDssMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
MmwDemo_edmaClose()
void MmwDemo_edmaClose (MmwDemo_DataPathObj * obj)
Description
Close EDMA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 274 of file dss_main.c.
References MmwDemo_DataPathObj_t::edmaHandle.
MmwDemo_edmaInit()
static void MmwDemo_edmaInit (MmwDemo_DataPathObj * obj, uint8_t instance)
Description
EDMA driver init
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Description
EDMA driver init
Parameters
[in] obj Pointer to data path object
[in] instance EDMA instance
Return values
Not Applicable.
Definition at line 179 of file dss_main.c.
References MmwDemo_DataPathObj_t::EDMA_errorInfo, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_dssInitTask().
MmwDemo_edmaOpen()
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj * obj, uint8_t instance) static
Description
Open EDMA driver instance
Parameters
[in] obj Pointer to data path object
[in] instance EDMA instance
Return values
Not Applicable.
Definition at line 233 of file dss_main.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_debugAssert, MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Referenced by MmwDemo_dssInitTask().
MmwDemo_sensorStopEpilog()
static void MmwDemo_sensorStopEpilog (void) static
Description
Epilog processing after sensor has stopped
Return values
None
Definition at line 286 of file dss_main.c.
References gMmwDssMCB, MmwDemo_DSS_MCB_t::initTaskHandle, MmwDemo_debugAssert, and MmwDemo_DSS_MCB_t::objDetDpmTaskHandle.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn().
MmwDemo_sleep()
void MmwDemo_sleep (void)
Description
Function to sleep the DSP using IDLE instruction. When DSP has no work left to do, the BIOS will be in Idle thread and will call this function.
Return values
Not Applicable.
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 831 of file dss_main.c.
MmwDemo_updateObjectDetStats()
void MmwDemo_updateObjectDetStats (DPC_ObjectDetection_Stats * currDpcStats, MmwDemo_output_message_stats * outputMsgStats) static
Description
Update stats based on the stats from DPC
Parameters
[in] currDpcStats Pointer to DPC status
[in] outputMsgStats Pointer to Output message stats
Return values
Not Applicable.
Definition at line 503 of file dss_main.c.
References DPC_ObjectDetection_Stats_t::frameStartTimeStamp, DPC_ObjectDetection_Stats_t::interChirpProcessingMargin, MmwDemo_output_message_stats_t::interChirpProcessingMargin, DPC_ObjectDetection_Stats_t::interFrameEndTimeStamp, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, DPC_ObjectDetection_Stats_t::interFrameStartTimeStamp, and DPC_ObjectDetection_Stats_t::subFramePreparationCycles.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
Variable Documentation
gDPC_ObjDetL1Heap
uint8_t gDPC_ObjDetL1Heap[MMWDEMO_OBJDET_L1RAM_SIZE]
Definition at line 106 of file dss_main.c.
Referenced by MmwDemo_dssInitTask().
gDPC_ObjDetL2Heap
uint8_t gDPC_ObjDetL2Heap[MMWDEMO_OBJDET_L2RAM_SIZE]
Definition at line 101 of file dss_main.c.
Referenced by MmwDemo_dssInitTask().
gHSRAM
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
Definition at line 135 of file dss_main.c.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
gMmwDssMCB
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 123 of file dss_main.c.
Referenced by main(), MmwDemo_DPC_ObjectDetection_dpmTask(), MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_dssInitTask(), MmwDemo_EDMA_errorCallbackFxn(), MmwDemo_EDMA_transferControllerErrorCallbackFxn(), and MmwDemo_sensorStopEpilog().
gMmwL3
uint8_t gMmwL3[SOC_L3RAM_SIZE]
L3 RAM buffer for object detection DPC
Definition at line 96 of file dss_main.c.
Referenced by MmwDemo_dssInitTask().
resultBuffer
DPM_Buffer resultBuffer
Global Variable for DPM result buffer.
Definition at line 129 of file dss_main.c.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
Copyright 2024, Texas Instruments Incorporated