xwr68xx/mmw/mss/mmw_mss.h File Reference
mmw_mss.h File Reference
This is the main header file for the Millimeter Wave Demo.
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/common/mmwave_error.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/uart/UART.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/demo/utils/mmwdemo_adcconfig.h>
#include <ti/demo/utils/mmwdemo_monitor.h>
#include <ti/demo/xwr68xx/mmw/include/mmw_output.h>
#include <ti/datapath/dpc/objectdetection/objdetrangehwa/objdetrangehwa.h>
#include <ti/demo/xwr68xx/mmw/include/mmw_config.h>
#include <ti/demo/xwr68xx/mmw/mss/mmw_lvds_stream.h>
Data Structures
struct MmwDemo_MSS_Stats_t
Millimeter Wave Demo statistics.
struct MmwDemo_BpmCfg_t
The structure specifies the BPM configuration.
struct MmwDemo_SubFrameCfg_t
Millimeter Wave Demo Data Path Information.
struct MmwDemo_SubFrameStats_t
Structure holds message stats information from data path.
struct MmwDemo_TaskHandles_t
Task handles storage structure.
struct MmwDemo_DataPathObj_t
struct MmwDemo_temperatureStats_t
Structure holds temperature information from Radar front end.
struct MmwDemo_calibDataHeader_t
Structure holds calibration save configuration used during sensor open.
struct MmwDemo_calibCfg_t
Structure holds calibration save configuration used during sensor open.
struct MmwDemo_calibData_t
Structure holds calibration restore configuration used during sensor open.
struct MmwDemo_MSS_MCB_t
Millimeter Wave Demo MCB.
Macros
#define MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG (-1)
For advanced frame config, below define means the configuration given is global at frame level and therefore it is broadcast to all sub-frames.
#define MMWDEMO_CFAR_THRESHOLD_ENCODING_FACTOR (100.0)
CFAR threshold encoding factor.
#define MMWDEMO_GUIMONSEL_OFFSET (offsetof(MmwDemo_SubFrameCfg, guiMonSel))
#define MMWDEMO_ADCBUFCFG_OFFSET (offsetof(MmwDemo_SubFrameCfg, adcBufCfg))
#define MMWDEMO_LVDSSTREAMCFG_OFFSET (offsetof(MmwDemo_SubFrameCfg, lvdsStreamCfg))
#define MMWDEMO_BPMCFG_OFFSET (offsetof(MmwDemo_SubFrameCfg, bpmCfg))
#define MMWDEMO_SUBFRAME_DSPDYNCFG_OFFSET
#define MMWDEMO_SUBFRAME_R4FDYNCFG_OFFSET
#define MMWDEMO_CFARCFGRANGE_OFFSET
#define MMWDEMO_CFARCFGDOPPLER_OFFSET
#define MMWDEMO_FOVRANGE_OFFSET
#define MMWDEMO_FOVDOPPLER_OFFSET
#define MMWDEMO_FOVAOA_OFFSET
#define MMWDEMO_EXTMAXVEL_OFFSET
#define MMWDEMO_MULTIOBJBEAMFORMING_OFFSET
#define MMWDEMO_CALIBDCRANGESIG_OFFSET
#define MMWDEMO_STATICCLUTTERREMOFVAL_OFFSET
#define MmwDemo_debugAssert(expression)
Typedefs
typedef enum MmwDemo_SensorState_e MmwDemo_SensorState
Millimeter Wave Demo Sensor State.
typedef struct MmwDemo_MSS_Stats_t MmwDemo_MSS_Stats
Millimeter Wave Demo statistics.
typedef struct MmwDemo_BpmCfg_t MmwDemo_BpmCfg
The structure specifies the BPM configuration.
typedef struct MmwDemo_SubFrameCfg_t MmwDemo_SubFrameCfg
Millimeter Wave Demo Data Path Information.
typedef struct MmwDemo_SubFrameStats_t MmwDemo_SubFrameStats
Structure holds message stats information from data path.
typedef struct MmwDemo_TaskHandles_t MmwDemo_taskHandles
Task handles storage structure.
typedef struct MmwDemo_DataPathObj_t MmwDemo_DataPathObj
typedef struct MmwDemo_temperatureStats_t MmwDemo_temperatureStats
Structure holds temperature information from Radar front end.
typedef struct MmwDemo_calibDataHeader_t MmwDemo_calibDataHeader
Structure holds calibration save configuration used during sensor open.
typedef struct MmwDemo_calibCfg_t MmwDemo_calibCfg
Structure holds calibration save configuration used during sensor open.
typedef struct MmwDemo_calibData_t MmwDemo_calibData
Structure holds calibration restore configuration used during sensor open.
typedef struct MmwDemo_MSS_MCB_t MmwDemo_MSS_MCB
Millimeter Wave Demo MCB.
Enumerations
enum MmwDemo_SensorState_e { MmwDemo_SensorState_INIT = 0, MmwDemo_SensorState_OPENED, MmwDemo_SensorState_STARTED, MmwDemo_SensorState_STOPPED }
Millimeter Wave Demo Sensor State.
Functions
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
int32_t MmwDemo_configSensor (void)
int32_t MmwDemo_startSensor (void)
void MmwDemo_stopSensor (void)
uint8_t MmwDemo_isAllCfgInPendingState (void)
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
void MmwDemo_resetStaticCfgPendingState (void)
void MmwDemo_CfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
void _MmwDemo_debugAssert (int32_t expression, const char *file, int32_t line)
Detailed Description
This is the main header file for the Millimeter Wave Demo.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mmw_mss.h.
Macro Definition Documentation
MMWDEMO_CFAR_THRESHOLD_ENCODING_FACTOR
#define MMWDEMO_CFAR_THRESHOLD_ENCODING_FACTOR (100.0)
CFAR threshold encoding factor.
Definition at line 71 of file mmw_mss.h.
MmwDemo_debugAssert
#define MmwDemo_debugAssert (expression)
Value:
                                         {                                      \
                                         _MmwDemo_debugAssert(expression,      \
                                                  __FILE__, __LINE__);         \
                                         DebugP_assert(expression);             \
                                        }
Definition at line 561 of file mmw_mss.h.
MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG
#define MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG (-1)
For advanced frame config, below define means the configuration given is global at frame level and therefore it is broadcast to all sub-frames.
Definition at line 67 of file mmw_mss.h.
Typedef Documentation
MmwDemo_BpmCfg
typedef struct MmwDemo_BpmCfg_t MmwDemo_BpmCfg
The structure specifies the BPM configuration.
The BPM is supported only for two azimuth transmit antennas. say A and B. In the even time slots (0,2,..), both transmit antennas should be configured to transmit with positive phase i.e (A,B) = (+, +) .* In the odd time slots (1,3..), the transmit antennas should be configured to transmit with phase (A,B) = (+, -)
The BPM decoding will produce the virtual antenna array in the order A,B [not B,A] which will be used for AoA processing. So user must make sure that the A,B mapping to the physical transmit antennas corresponds to the intended virtual antenna order. On the 6843 EVM, this means A = Tx1 and B = Tx3
Please note: mmwave link use TX antenna index starting from 0.
MmwDemo_calibCfg
typedef struct MmwDemo_calibCfg_t MmwDemo_calibCfg
Structure holds calibration save configuration used during sensor open.
The structure holds calibration save configuration.
MmwDemo_calibData
typedef struct MmwDemo_calibData_t MmwDemo_calibData
Structure holds calibration restore configuration used during sensor open.
The structure holds calibration restore configuration.
MmwDemo_calibDataHeader
typedef struct MmwDemo_calibDataHeader_t MmwDemo_calibDataHeader
Structure holds calibration save configuration used during sensor open.
The structure holds calibration save configuration.
MmwDemo_DataPathObj
typedef struct MmwDemo_DataPathObj_t MmwDemo_DataPathObj
MmwDemo_MSS_MCB
typedef struct MmwDemo_MSS_MCB_t MmwDemo_MSS_MCB
Millimeter Wave Demo MCB.
The structure is used to hold all the relevant information for the Millimeter Wave demo
MmwDemo_MSS_Stats
typedef struct MmwDemo_MSS_Stats_t MmwDemo_MSS_Stats
Millimeter Wave Demo statistics.
The structure is used to hold the statistics information for the Millimeter Wave demo
MmwDemo_SensorState
typedef enum MmwDemo_SensorState_e MmwDemo_SensorState
Millimeter Wave Demo Sensor State.
The enumeration is used to define the sensor states used in mmwDemo
MmwDemo_SubFrameCfg
typedef struct MmwDemo_SubFrameCfg_t MmwDemo_SubFrameCfg
Millimeter Wave Demo Data Path Information.
The structure is used to hold all the relevant information for the data path.
MmwDemo_SubFrameStats
typedef struct MmwDemo_SubFrameStats_t MmwDemo_SubFrameStats
Structure holds message stats information from data path.
The structure holds stats information. This is a payload of the TLV message item that holds stats information.
MmwDemo_taskHandles
typedef struct MmwDemo_TaskHandles_t MmwDemo_taskHandles
Task handles storage structure.
MmwDemo_temperatureStats
typedef struct MmwDemo_temperatureStats_t MmwDemo_temperatureStats
Structure holds temperature information from Radar front end.
The structure holds temperature stats information.
Enumeration Type Documentation
MmwDemo_SensorState_e
enum MmwDemo_SensorState_e
Millimeter Wave Demo Sensor State.
The enumeration is used to define the sensor states used in mmwDemo
Enumerator
MmwDemo_SensorState_INIT
Inital state after sensor is initialized.
MmwDemo_SensorState_OPENED
Inital state after sensor is post RF init.
MmwDemo_SensorState_STARTED
Indicates sensor is started.
MmwDemo_SensorState_STOPPED
State after sensor has completely stopped.
Definition at line 127 of file mmw_mss.h.
Function Documentation
_MmwDemo_debugAssert()
void _MmwDemo_debugAssert (int32_t expression, const char * file, int32_t line)
Description
Send assert information through CLI.
Parameters
[in] expression Expression for evaluation
[in] file C file that caused assertion
[in] line Line number in C fine that caused assertion
Definition at line 987 of file mss_main.c.
References CLI_write().
MmwDemo_CfgUpdate()
void MmwDemo_CfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
Description
Utility function to apply configuration to specified sub-frame
Parameters
[in] srcPtr Pointer to configuration
[in] offset Offset of configuration within the parent structure
[in] size Size of configuration
[in] subFrameNum Sub-frame Number (0 based) to apply to, broadcast to all sub-frames if special code MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG
Return values
Success - 0
Error - <0
Definition at line 1281 of file mss_main.c.
References gMmwMssMCB, MmwDemo_setSubFramePendingState(), MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), and MmwDemo_CLIMultiObjBeamForming().
MmwDemo_configSensor()
int32_t MmwDemo_configSensor (void)
Description
MMW demo helper Function to configure sensor. User need to fill gMmwMssMCB.cfg.ctrlCfg and add profiles/chirp to mmWave before calling this function
Return values
Success - 0
Error - <0
Definition at line 3519 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MMWave_config(), MMWave_decodeError(), MmwDemo_bpmConfig(), and MmwDemo_dataPathConfig().
Referenced by MmwDemo_CLISensorStart().
MmwDemo_isAllCfgInNonPendingState()
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in non-pending (cleared) state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in non-pending state, else return 0
Definition at line 1248 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, MmwDemo_isDynObjDetCfgInNonPendingState(), MmwDemo_isDynObjDetCommonCfgInNonPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_isAllCfgInPendingState()
uint8_t MmwDemo_isAllCfgInPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in pending state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in pending state, else return 0
Definition at line 1222 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, MmwDemo_isDynObjDetCfgPendingState(), MmwDemo_isDynObjDetCommonCfgPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_openSensor()
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
Description
mmw demo helper Function to do one time sensor initialization. User need to fill gMmwMssMCB.cfg.openCfg before calling this function
Parameters
[in] isFirstTimeOpen If true then issues MMwave_open
Return values
Success - 0
Error - <0
Definition at line 3358 of file mss_main.c.
References MmwDemo_MSS_MCB_t::calibCfg, MmwDemo_calibData_t::calibData, MmwDemo_calibCfg_t::calibDataHdr, MMWave_OpenCfg_t::calibMonTimeUnit, MmwDemo_MSS_MCB_t::cfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_OpenCfg_t::customCalibrationEnableMask, MMWave_OpenCfg_t::disableFrameStartAsyncEvent, MMWave_OpenCfg_t::disableFrameStopAsyncEvent, MMWave_OpenCfg_t::freqLimitHigh, MMWave_OpenCfg_t::freqLimitLow, gCalibDataStorage, gMmwMssMCB, gRFLdoBypassCfg, MMWave_decodeError(), MMWave_open(), MmwDemo_calibRestore(), MmwDemo_calibSave(), MmwDemo_dataPathOpen(), MmwDemo_mssSetHsiClk(), MmwDemo_Cfg_t::openCfg, MmwDemo_calibData_t::phaseShiftCalibData, MMWave_CalibrationData_t::ptrCalibData, MMWave_CalibrationData_t::ptrPhaseShiftCalibData, MmwDemo_calibCfg_t::restoreEnable, MmwDemo_calibCfg_t::saveEnable, and MMWave_OpenCfg_t::useCustomCalibration.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_resetStaticCfgPendingState()
void MmwDemo_resetStaticCfgPendingState (void)
Description
Resets (clears) all pending static (non-dynamic) configuration
Definition at line 1199 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStop().
MmwDemo_startSensor()
int32_t MmwDemo_startSensor (void)
Description
mmw demo helper Function to start sensor.
Return values
Success - 0
Error - <0
Definition at line 3560 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_CtrlCfg_t::dfeDataOutputMode, gMmwMssMCB, gts, gtsIdx, MMWave_decodeError(), MMWave_start(), MmwDemo_dataPathStart(), MmwDemo_debugAssert, MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::sensorStartCount, and MmwDemo_platformCfg_t::SensorStatusGPIO.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_stopSensor()
void MmwDemo_stopSensor (void)
Description
Stops the RF and datapath for the sensor. Blocks until both operation are completed. Prints epilog at the end.
Return values
None
Definition at line 3672 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_MSS_MCB_t::DPMstopSemHandle, gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_DISABLED, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteHwSession(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_mmWaveCtrlStop(), MmwDemo_sensorStopEpilog(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_Cfg_t::platformCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_MSS_MCB_t::sensorStartCount, MmwDemo_platformCfg_t::SensorStatusGPIO, MmwDemo_MSS_MCB_t::sensorStopCount, MmwDemo_MSS_MCB_t::subFrameCfg, and MmwDemo_LVDSStream_MCB::swSessionHandle.
Referenced by MmwDemo_CLISensorStop().
Copyright 2024, Texas Instruments Incorporated