xwr68xx/mmw/mss/mmw_lvds_stream.c File Reference
mmw_lvds_stream.c File Reference
Implements LVDS stream functionality.
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/System.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/drivers/soc/soc.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/osal/MemoryP.h>
#include <ti/drivers/adcbuf/ADCBuf.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/cbuff/cbuff.h>
#include <ti/utils/hsiheader/hsiheader.h>
#include <ti/demo/xwr68xx/mmw/mss/mmw_mss.h>
#include <ti/demo/xwr68xx/mmw/mmw_res.h>
Functions
void MmwDemo_LVDSStream_EDMAInit (void)
int32_t MmwDemo_LVDSStreamInit (void)
static void MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static void MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel (CBUFF_EDMAChannelCfg *ptrEDMACfg)
static void MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel (CBUFF_EDMAChannelCfg *ptrEDMACfg)
void MmwDemo_LVDSStreamDeleteHwSession (void)
void MmwDemo_LVDSStreamDeleteSwSession (void)
static void MmwDemo_LVDSStream_HwTriggerFrameDone (CBUFF_SessionHandle sessionHandle)
static void MmwDemo_LVDSStream_SwTriggerFrameDone (CBUFF_SessionHandle sessionHandle)
int32_t MmwDemo_LVDSStreamHwConfig (uint8_t subFrameIndx)
int32_t MmwDemo_LVDSStreamSwConfig (uint32_t numObjOut, DPIF_PointCloudCartesian *objOut, DPIF_PointCloudSideInfo *objOutSideInfo)
void MmwDemo_configLVDSHwData (uint8_t subFrameIndx)
Variables
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
Implements LVDS stream functionality.
NOTE: (C) Copyright 2019 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mmw_lvds_stream.c.
Function Documentation
MmwDemo_configLVDSHwData()
void MmwDemo_configLVDSHwData (uint8_t subFrameIndx)
Description
High level API for configuring Hw session. Deletes h/w session if it exists, configures desired configuration input and activates the h/w session
Parameters
[in] subFrameIndx Index of sub-frame
Return values
None
Definition at line 785 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteHwSession(), and MmwDemo_LVDSStreamHwConfig().
Referenced by MmwDemo_dataPathStart(), and MmwDemo_handleObjectDetResult().
MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel()
static void MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
Function that allocates CBUFF-EDMA channel
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Definition at line 207 of file mmw_lvds_stream.c.
References MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_1, and MmwDemo_debugAssert.
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), and MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel().
MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel()
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel allocation function which allocates EDMA channels for CBUFF HW Session
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Return values
Success - 0
Error - <0
Definition at line 246 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_MSS_MCB_t::lvdsStream, MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL, and MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel().
Referenced by MmwDemo_LVDSStreamHwConfig().
MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel()
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel allocation function which allocates EDMA channels for CBUFF SW Session
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Return values
Success - 0
Error - <0
Definition at line 304 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_MSS_MCB_t::lvdsStream, MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL, MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel(), MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStreamSwConfig().
MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel()
static void MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel (CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel free function which frees EDMA channels which had been allocated for use by a CBUFF HW Session
Return values
Not applicable
Definition at line 354 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_MSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MmwDemo_debugAssert, and MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL.
Referenced by MmwDemo_LVDSStreamHwConfig().
MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel()
static void MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel (CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel free function which frees EDMA channels which had been allocated for use by a CBUFF SW Session
Return values
Not applicable
Definition at line 397 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_MSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MmwDemo_debugAssert, MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL, MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStreamSwConfig().
MmwDemo_LVDSStream_EDMAInit()
void MmwDemo_LVDSStream_EDMAInit (void)
Description
This function initializes/configures the LVDS streaming EDMA resources.
Return values
Success - 0
Error - <0
Definition at line 80 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_MSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_0, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_1, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_10, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_2, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_3, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_4, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_5, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_6, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_7, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_8, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_9, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_1, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_10, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_2, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_3, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_4, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_5, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_6, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_7, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_8, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_9, MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_0, MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_1, MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_2, MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_1, MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_2, MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStreamInit().
MmwDemo_LVDSStream_HwTriggerFrameDone()
static void MmwDemo_LVDSStream_HwTriggerFrameDone (CBUFF_SessionHandle sessionHandle) static
Description
This is the registered callback function which is invoked after the frame done interrupt is received for the hardware session.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 520 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwFrameDoneCount, MmwDemo_LVDSStream_MCB::hwFrameDoneSemHandle, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_LVDSStreamHwConfig().
MmwDemo_LVDSStream_SwTriggerFrameDone()
static void MmwDemo_LVDSStream_SwTriggerFrameDone (CBUFF_SessionHandle sessionHandle) static
Description
This is the registered callback function which is invoked after the frame done interrupt is received for the SW session.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 570 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MSS_MCB_t::lvdsStream, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_LVDSStream_MCB::swFrameDoneCount, and MmwDemo_LVDSStream_MCB::swFrameDoneSemHandle.
Referenced by MmwDemo_LVDSStreamSwConfig().
MmwDemo_LVDSStreamDeleteHwSession()
void MmwDemo_LVDSStreamDeleteHwSession (void)
Description
This function deletes the hardware session and any HSI header associated with it.
Return values
Not applicable
Definition at line 441 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LVDSStream_MCB::isHwSessionHSIHeaderAllocated, MmwDemo_MSS_MCB_t::lvdsStream, and MmwDemo_debugAssert.
Referenced by MmwDemo_configLVDSHwData(), and MmwDemo_stopSensor().
MmwDemo_LVDSStreamDeleteSwSession()
void MmwDemo_LVDSStreamDeleteSwSession (void)
Description
This function deletes the SW session and any HSI header associated with it.
Return values
Not applicable
Definition at line 482 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::swSessionHSIHeader.
Referenced by MmwDemo_stopSensor(), and MmwDemo_transferLVDSUserData().
MmwDemo_LVDSStreamHwConfig()
int32_t MmwDemo_LVDSStreamHwConfig (uint8_t subFrameIndx)
Description
This is the LVDS streaming config function. It configures the sessions for the LVDS streaming.
Return values
Success - 0
Error - <0
Definition at line 621 of file mmw_lvds_stream.c.
References MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::chirpThreshold, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::edmaHandle, gMmwMssMCB, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_LVDSStream_MCB::isHwSessionHSIHeaderAllocated, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_ADC, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_CP_ADC_CQ, MmwDemo_debugAssert, MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel(), MmwDemo_LVDSStream_HwTriggerFrameDone(), MmwDemo_SubFrameCfg_t::numAdcSamples, MmwDemo_SubFrameCfg_t::numChirpsPerSubFrame, MmwDemo_SubFrameCfg_t::satMonTotalSize, MmwDemo_SubFrameCfg_t::sigImgMonTotalSize, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_configLVDSHwData().
MmwDemo_LVDSStreamInit()
int32_t MmwDemo_LVDSStreamInit (void)
Description
This is the LVDS streaming init function. It initializes the necessary modules that implement the streaming.
Return values
Success - 0
Error - <0
Definition at line 130 of file mmw_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwFrameDoneSemHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStream_EDMAInit(), MmwDemo_MSS_MCB_t::socHandle, and MmwDemo_LVDSStream_MCB::swFrameDoneSemHandle.
Referenced by MmwDemo_initTask().
MmwDemo_LVDSStreamSwConfig()
int32_t MmwDemo_LVDSStreamSwConfig (uint32_t numObjOut, DPIF_PointCloudCartesian * objOut, DPIF_PointCloudSideInfo * objOutSideInfo)
Description
This is the LVDS sw streaming config function. It configures the sw session for the LVDS streaming.
Parameters
[in] numObjOut Number of detected objects to stream out
[in] objOut Pointer to detected objects point cloud
[in] objOutSideInfo Pointer to detected objects side information
Return values
Success - 0
Error - <0
Definition at line 715 of file mmw_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::edmaHandle, gMmwMssMCB, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel(), MmwDemo_LVDSStream_SwTriggerFrameDone(), MmwDemo_LVDSStream_MCB::swSessionHandle, MmwDemo_LVDSStream_MCB::swSessionHSIHeader, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_transferLVDSUserData().
Variable Documentation
gMmwMssMCB
MmwDemo_MSS_MCB gMmwMssMCB extern
Global Variable for tracking information required by the mmw Demo.
Definition at line 684 of file mss_main.c.
Referenced by main(), MmwDemo_bpmConfig(), MmwDemo_calibInit(), MmwDemo_calibRestore(), MmwDemo_calibSave(), MmwDemo_CfgUpdate(), MmwDemo_configCQ(), MmwDemo_configLVDSHwData(), MmwDemo_configSensor(), MmwDemo_dataPathConfig(), MmwDemo_dataPathOpen(), MmwDemo_dataPathStart(), MmwDemo_dataPathStop(), MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_DPM_ioctl_blocking(), MmwDemo_EDMA_errorCallbackFxn(), MmwDemo_EDMA_transferControllerErrorCallbackFxn(), MmwDemo_eventCallbackFxn(), MmwDemo_getTemperatureReport(), MmwDemo_handleObjectDetResult(), MmwDemo_initTask(), MmwDemo_isAllCfgInNonPendingState(), MmwDemo_isAllCfgInPendingState(), MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAInit(), MmwDemo_LVDSStream_HwTriggerFrameDone(), MmwDemo_LVDSStream_SwTriggerFrameDone(), MmwDemo_LVDSStreamDeleteHwSession(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_LVDSStreamHwConfig(), MmwDemo_LVDSStreamInit(), MmwDemo_LVDSStreamSwConfig(), MmwDemo_mmWaveCtrlStop(), MmwDemo_mmWaveCtrlTask(), mmwDemo_mssDPMTask(), MmwDemo_openSensor(), MmwDemo_processPendingDynamicCfgCommands(), MmwDemo_resetStaticCfgPendingState(), MmwDemo_sensorStopEpilog(), MmwDemo_startSensor(), MmwDemo_stopSensor(), MmwDemo_transferLVDSUserData(), and MmwDemo_transmitProcessedOutput().
Copyright 2024, Texas Instruments Incorporated