xwr68xx/mmw/mss/mmw_lvds_stream.h File Reference
mmw_lvds_stream.h File Reference
LVDS stream header file.
#include <ti/drivers/cbuff/cbuff.h>
#include <ti/utils/hsiheader/hsiheader.h>
Data Structures
struct MmwDemo_LVDSUserDataHeader
LVDS streaming user data header.
struct MmwDemo_LVDSStream_MCB
LVDS streaming MCB.
Macros
#define MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL 11U
This is the maximum number of EDMA Channels which is used by the HW Session.
#define MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL 3U
This is the maximum number of EDMA Channels which is used by the SW Session.
Typedefs
typedef struct MmwDemo_LVDSUserDataHeader MmwDemo_LVDSUserDataHeader_t
LVDS streaming user data header.
typedef struct MmwDemo_LVDSStream_MCB MmwDemo_LVDSStream_MCB_t
LVDS streaming MCB.
Functions
int32_t MmwDemo_LVDSStreamInit (void)
int32_t MmwDemo_LVDSStreamHwConfig (uint8_t subFrameIndx)
int32_t MmwDemo_LVDSStreamSwConfig (uint32_t numObjOut, DPIF_PointCloudCartesian *objOut, DPIF_PointCloudSideInfo *objOutSideInfo)
void MmwDemo_configLVDSHwData (uint8_t subFrameIndx)
void MmwDemo_LVDSStreamDeleteHwSession (void)
void MmwDemo_LVDSStreamDeleteSwSession (void)
Detailed Description
LVDS stream header file.
NOTE: (C) Copyright 2019 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mmw_lvds_stream.h.
Macro Definition Documentation
MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL
#define MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL 11U
This is the maximum number of EDMA Channels which is used by the HW Session.
Definition at line 53 of file mmw_lvds_stream.h.
MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL
#define MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL 3U
This is the maximum number of EDMA Channels which is used by the SW Session.
Definition at line 59 of file mmw_lvds_stream.h.
Typedef Documentation
MmwDemo_LVDSStream_MCB_t
typedef struct MmwDemo_LVDSStream_MCB MmwDemo_LVDSStream_MCB_t
LVDS streaming MCB.
The LVDS streaming MCB
MmwDemo_LVDSUserDataHeader_t
typedef struct MmwDemo_LVDSUserDataHeader MmwDemo_LVDSUserDataHeader_t
LVDS streaming user data header.
The LVDS SW streaming user data header
Function Documentation
MmwDemo_configLVDSHwData()
void MmwDemo_configLVDSHwData (uint8_t subFrameIndx)
Description
High level API for configuring Hw session. Deletes h/w session if it exists, configures desired configuration input and activates the h/w session
Parameters
[in] subFrameIndx Index of sub-frame
Return values
None
Definition at line 785 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteHwSession(), and MmwDemo_LVDSStreamHwConfig().
Referenced by MmwDemo_dataPathStart(), and MmwDemo_handleObjectDetResult().
MmwDemo_LVDSStreamDeleteHwSession()
void MmwDemo_LVDSStreamDeleteHwSession (void)
Description
This function deletes the hardware session and any HSI header associated with it.
Return values
Not applicable
Definition at line 441 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LVDSStream_MCB::isHwSessionHSIHeaderAllocated, MmwDemo_MSS_MCB_t::lvdsStream, and MmwDemo_debugAssert.
Referenced by MmwDemo_configLVDSHwData(), and MmwDemo_stopSensor().
MmwDemo_LVDSStreamDeleteSwSession()
void MmwDemo_LVDSStreamDeleteSwSession (void)
Description
This function deletes the SW session and any HSI header associated with it.
Return values
Not applicable
Definition at line 482 of file mmw_lvds_stream.c.
References gMmwMssMCB, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::swSessionHSIHeader.
Referenced by MmwDemo_stopSensor(), and MmwDemo_transferLVDSUserData().
MmwDemo_LVDSStreamHwConfig()
int32_t MmwDemo_LVDSStreamHwConfig (uint8_t subFrameIndx)
Description
This is the LVDS streaming config function. It configures the sessions for the LVDS streaming.
Return values
Success - 0
Error - <0
Definition at line 621 of file mmw_lvds_stream.c.
References MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::chirpThreshold, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::edmaHandle, gMmwMssMCB, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_LVDSStream_MCB::isHwSessionHSIHeaderAllocated, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_ADC, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_CP_ADC_CQ, MmwDemo_debugAssert, MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel(), MmwDemo_LVDSStream_HwTriggerFrameDone(), MmwDemo_SubFrameCfg_t::numAdcSamples, MmwDemo_SubFrameCfg_t::numChirpsPerSubFrame, MmwDemo_SubFrameCfg_t::satMonTotalSize, MmwDemo_SubFrameCfg_t::sigImgMonTotalSize, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_configLVDSHwData().
MmwDemo_LVDSStreamInit()
int32_t MmwDemo_LVDSStreamInit (void)
Description
This is the LVDS streaming init function. It initializes the necessary modules that implement the streaming.
Return values
Success - 0
Error - <0
Definition at line 130 of file mmw_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwFrameDoneSemHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStream_EDMAInit(), MmwDemo_MSS_MCB_t::socHandle, and MmwDemo_LVDSStream_MCB::swFrameDoneSemHandle.
Referenced by MmwDemo_initTask().
MmwDemo_LVDSStreamSwConfig()
int32_t MmwDemo_LVDSStreamSwConfig (uint32_t numObjOut, DPIF_PointCloudCartesian * objOut, DPIF_PointCloudSideInfo * objOutSideInfo)
Description
This is the LVDS sw streaming config function. It configures the sw session for the LVDS streaming.
Parameters
[in] numObjOut Number of detected objects to stream out
[in] objOut Pointer to detected objects point cloud
[in] objOutSideInfo Pointer to detected objects side information
Return values
Success - 0
Error - <0
Definition at line 715 of file mmw_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::edmaHandle, gMmwMssMCB, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel(), MmwDemo_LVDSStream_SwTriggerFrameDone(), MmwDemo_LVDSStream_MCB::swSessionHandle, MmwDemo_LVDSStream_MCB::swSessionHSIHeader, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_transferLVDSUserData().
Copyright 2024, Texas Instruments Incorporated