xwr68xx/mmw/mss/mss_main.c File Reference
mss_main.c File Reference
This is the main file which implements the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/drivers/pinmux/pinmux.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/control/dpm/dpm.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/uart/UART.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/demo/xwr68xx/mmw/include/mmw_config.h>
#include <ti/demo/utils/mmwdemo_monitor.h>
#include <ti/demo/xwr68xx/mmw/include/mmw_output.h>
#include <ti/demo/xwr68xx/mmw/mmw_res.h>
#include <ti/demo/xwr68xx/mmw/mss/mmw_mss.h>
#include <ti/demo/utils/mmwdemo_rfparser.h>
#include <ti/demo/utils/mmwdemo_adcconfig.h>
#include <ti/demo/utils/mmwdemo_flash.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
Macros
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
#define DPC_OBJDET_R4F_INSTANCEID (0xFEEDFEED)
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0x800U
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x1000U
#define MMW_DEMO_CQ_DATA_ALIGNMENT 16U
#define MMWDEMO_OBJDET_LOCALRAM_SIZE (4U * 1024U)
#define MMWDEMO_CALIB_FLASH_SIZE 4096
#define MMWDEMO_CALIB_STORE_MAGIC (0x7CB28DF9U)
Functions
void MmwDemo_CLIInit (uint8_t taskPriority)
static void MmwDemo_dataPathOpen (void)
static int32_t MmwDemo_dataPathConfig (void)
static void MmwDemo_dataPathStart (void)
static void MmwDemo_dataPathStop (void)
static void MmwDemo_handleObjectDetResult (DPM_Buffer *ptrResult)
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1)
static void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult *result, MmwDemo_output_message_stats *timingInfo)
Transmits detection data over UART.
static void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static int32_t MmwDemo_DPM_ioctl_blocking (DPM_Handle handle, uint32_t cmd, void *arg, uint32_t argLen)
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx)
static void MmwDemo_initTask (UArg arg0, UArg arg1)
static void MmwDemo_platformInit (MmwDemo_platformCfg *config)
static void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
static int32_t MmwDemo_mmWaveCtrlStop (void)
static int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
void MmwDemo_sleep (void)
static void MmwDemo_edmaInit (MmwDemo_DataPathObj *obj, uint8_t instance)
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj *obj, uint8_t instance)
static void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
static void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
static int32_t MmwDemo_configCQ (MmwDemo_SubFrameCfg *subFrameCfg, uint8_t numChirpsPerChirpEvent, uint8_t validProfileIdx)
static int32_t MmwDemo_calibInit (void)
static int32_t MmwDemo_calibSave (MmwDemo_calibDataHeader *ptrCalibDataHdr, MmwDemo_calibData *ptrCalibrationData)
static int32_t MmwDemo_calibRestore (MmwDemo_calibData *calibrationData)
void MmwDemo_edmaClose (MmwDemo_DataPathObj *obj)
static void MmwDemo_hwaInit (MmwDemo_DataPathObj *obj)
static void MmwDemo_hwaOpen (MmwDemo_DataPathObj *obj, SOC_Handle socHandle)
void MmwDemo_hwaClose (MmwDemo_DataPathObj *obj)
void _MmwDemo_debugAssert (int32_t expression, const char *file, int32_t line)
static void MmwDemo_setSubFramePendingState (MmwDemo_SubFrameCfg *subFrameCfg, uint32_t offset)
static uint8_t MmwDemo_isDynObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isDynObjDetCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static uint8_t MmwDemo_isDynObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isDynObjDetCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static void MmwDemo_resetDynObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static void MmwDemo_resetDynObjDetCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
void MmwDemo_resetStaticCfgPendingState (void)
uint8_t MmwDemo_isAllCfgInPendingState (void)
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
void MmwDemo_CfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
void MmwDemo_getTemperatureReport ()
int32_t MmwDemo_bpmConfig (void)
static uint16_t MmwDemo_convertCfarToLinear (uint16_t codedCfarVal, uint8_t numVirtualAntennas)
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
void MmwDemo_transferLVDSUserData (uint8_t subFrameIndx, DPC_ObjectDetection_ExecuteResult *dpcResults)
static void mmwDemo_mssDPMTask (UArg arg0, UArg arg1)
int32_t MmwDemo_mssSetHsiClk (void)
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
int32_t MmwDemo_configSensor (void)
int32_t MmwDemo_startSensor (void)
static void MmwDemo_sensorStopEpilog (void)
void MmwDemo_stopSensor (void)
static void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx)
static void MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn (uint8_t subFrameIndx)
int main (void)
Variables
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
uint8_t gDPCTCM [MMWDEMO_OBJDET_LOCALRAM_SIZE]
uint8_t gMmwL3 [SOC_L3RAM_SIZE]
rlRfLdoBypassCfg_t gRFLdoBypassCfg
Global Variable for LDO BYPASS config, PLease consult your board/EVM user guide before changing the values here.
MmwDemo_calibData gCalibDataStorage
uint32_t gts [100]
uint32_t gtsIdx = 0
Detailed Description
This is the main file which implements the millimeter wave Demo.
NOTE: (C) Copyright 2019 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mss_main.c.
Macro Definition Documentation
DPC_OBJDET_R4F_INSTANCEID
#define DPC_OBJDET_R4F_INSTANCEID (0xFEEDFEED)
Definition at line 664 of file mss_main.c.
MMW_DEMO_CQ_DATA_ALIGNMENT
#define MMW_DEMO_CQ_DATA_ALIGNMENT 16U
Definition at line 674 of file mss_main.c.
MMW_DEMO_CQ_RXSAT_ADDR_OFFSET
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x1000U
Definition at line 671 of file mss_main.c.
MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0x800U
Definition at line 670 of file mss_main.c.
MMWDEMO_CALIB_FLASH_SIZE
#define MMWDEMO_CALIB_FLASH_SIZE 4096
Definition at line 719 of file mss_main.c.
MMWDEMO_CALIB_STORE_MAGIC
#define MMWDEMO_CALIB_STORE_MAGIC (0x7CB28DF9U)
Definition at line 720 of file mss_main.c.
MMWDEMO_CLI_TASK_PRIORITY
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
CLI task must be at a lower priority than object detection dpm task priority because the dynamic CLI command handling in the objection detection dpm task assumes CLI task is held back during this processing. The alternative is to use a semaphore between the two tasks.
Definition at line 656 of file mss_main.c.
MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
Definition at line 657 of file mss_main.c.
MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
Definition at line 658 of file mss_main.c.
MMWDEMO_OBJDET_LOCALRAM_SIZE
#define MMWDEMO_OBJDET_LOCALRAM_SIZE (4U * 1024U)
HSRAM for processing results
TCMB RAM buffer for object detection DPC
Definition at line 697 of file mss_main.c.
Function Documentation
_MmwDemo_debugAssert()
void _MmwDemo_debugAssert (int32_t expression, const char * file, int32_t line)
Description
Send assert information through CLI.
Parameters
[in] expression Expression for evaluation
[in] file C file that caused assertion
[in] line Line number in C fine that caused assertion
Definition at line 987 of file mss_main.c.
References CLI_write().
main()
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 4655 of file mss_main.c.
References gMmwMssMCB, MmwDemo_TaskHandles_t::initTask, MmwDemo_debugAssert, MmwDemo_initTask(), MmwDemo_MSS_MCB_t::socHandle, and MmwDemo_MSS_MCB_t::taskHandles.
MmwDemo_bpmConfig()
int32_t MmwDemo_bpmConfig (void)
Description
Function that configures the BPM chirps based on the stored BPM CLI commands. The MMW demo supports only a fixed BPM scheme and this scheme is implemented by this function.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1752 of file mss_main.c.
References MmwDemo_SubFrameCfg_t::bpmCfg, MmwDemo_MSS_MCB_t::cfg, MmwDemo_BpmCfg_t::chirp0Idx, MmwDemo_BpmCfg_t::chirp1Idx, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MmwDemo_BpmCfg_t::isEnabled, MMWave_addBpmChirp(), MmwDemo_RFParser_getNumSubFrames(), and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_configSensor().
MmwDemo_calibInit()
static int32_t MmwDemo_calibInit (void) static
Description
Calibration save/restore initialization
Return values
Success - 0
Error - <0
Definition at line 3851 of file mss_main.c.
References MmwDemo_MSS_MCB_t::calibCfg, MmwDemo_calibCfg_t::calibDataHdr, MmwDemo_calibDataHeader_t::dataLen, gCalibDataStorage, gMmwMssMCB, MmwDemo_calibDataHeader_t::hdrLen, MmwDemo_calibDataHeader_t::linkVer, MmwDemo_calibDataHeader_t::magic, MMWDEMO_CALIB_FLASH_SIZE, MMWDEMO_CALIB_STORE_MAGIC, MmwDemo_calibDataHeader_t::radarSSVer, and MmwDemo_calibCfg_t::sizeOfCalibDataStorage.
Referenced by MmwDemo_initTask().
MmwDemo_calibRestore()
static int32_t MmwDemo_calibRestore (MmwDemo_calibData * ptrCalibData) static
Description
This function reads calibration data from flash and send it to front end through MMWave_open()
Parameters
[in] ptrCalibData Pointer to Calibration data
Return values
Success - 0
Error - <0
Definition at line 3941 of file mss_main.c.
References MmwDemo_MSS_MCB_t::calibCfg, MmwDemo_calibCfg_t::calibDataHdr, MmwDemo_calibData_t::calibDataHdr, MmwDemo_calibDataHeader_t::dataLen, MmwDemo_calibCfg_t::flashOffset, gMmwMssMCB, MmwDemo_calibDataHeader_t::hdrLen, MmwDemo_calibDataHeader_t::linkVer, MMWDEMO_CALIB_STORE_MAGIC, and MmwDemo_calibDataHeader_t::radarSSVer.
Referenced by MmwDemo_openSensor().
MmwDemo_calibSave()
static int32_t MmwDemo_calibSave (MmwDemo_calibDataHeader * ptrCalibDataHdr, MmwDemo_calibData * ptrCalibrationData) static
Description
This function retrieves the calibration data from front end and saves it in flash.
Parameters
[in] ptrCalibDataHdr Pointer to Calibration data header
[in] ptrCalibrationData Pointer to Calibration data
Return values
Success - 0
Error - <0
Definition at line 3907 of file mss_main.c.
References MmwDemo_MSS_MCB_t::calibCfg, MmwDemo_calibData_t::calibDataHdr, MmwDemo_calibCfg_t::flashOffset, and gMmwMssMCB.
Referenced by MmwDemo_openSensor().
MmwDemo_CfgUpdate()
void MmwDemo_CfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
Description
Utility function to apply configuration to specified sub-frame
Parameters
[in] srcPtr Pointer to configuration
[in] offset Offset of configuration within the parent structure
[in] size Size of configuration
[in] subFrameNum Sub-frame Number (0 based) to apply to, broadcast to all sub-frames if special code MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG
Return values
Success - 0
Error - <0
Definition at line 1281 of file mss_main.c.
References gMmwMssMCB, MmwDemo_setSubFramePendingState(), MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), and MmwDemo_CLIMultiObjBeamForming().
MmwDemo_CLIInit()
void MmwDemo_CLIInit (uint8_t taskPriority)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 1375 of file mmw_cli.c.
References CLI_open(), MmwDemo_MSS_MCB_t::commandUartHandle, MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDataSaveRestore(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIConfigDataPort(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLIQueryDemoStatus(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), and MmwDemo_MSS_MCB_t::socHandle.
Referenced by MmwDemo_initTask().
MmwDemo_configCQ()
static int32_t MmwDemo_configCQ (MmwDemo_SubFrameCfg * subFrameCfg, uint8_t numChirpsPerChirpEvent, uint8_t validProfileIdx) static
Description
Function to configure CQ.
Parameters
[in] subFrameCfg Pointer to sub-frame config
[in] numChirpsPerChirpEvent number of chirps per chirp event
[in] validProfileIdx valid profile index
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1856 of file mss_main.c.
References MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_MSS_MCB_t::anaMonCfg, MmwDemo_MSS_MCB_t::cqSatMonCfg, MmwDemo_MSS_MCB_t::cqSigImgMonCfg, gMmwMssMCB, MMW_DEMO_CQ_DATA_ALIGNMENT, MMW_DEMO_CQ_RXSAT_ADDR_OFFSET, MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET, MmwDemo_debugAssert, MmwDemo_SubFrameCfg_t::satMonTotalSize, and MmwDemo_SubFrameCfg_t::sigImgMonTotalSize.
Referenced by MmwDemo_dataPathConfig().
MmwDemo_configSensor()
int32_t MmwDemo_configSensor (void)
Description
MMW demo helper Function to configure sensor. User need to fill gMmwMssMCB.cfg.ctrlCfg and add profiles/chirp to mmWave before calling this function
Return values
Success - 0
Error - <0
Definition at line 3519 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MMWave_config(), MMWave_decodeError(), MmwDemo_bpmConfig(), and MmwDemo_dataPathConfig().
Referenced by MmwDemo_CLISensorStart().
MmwDemo_convertCfarToLinear()
static uint16_t MmwDemo_convertCfarToLinear (uint16_t codedCfarVal, uint8_t numVirtualAntennas) static
Description
Utility function to convert the CFAR threshold from a CLI encoded dB value to a linear value as expected by the CFAR DPU
Parameters
[in] codedCfarVal CFAR threshold in dB as encoded in the CLI
[in] numVirtualAntennas Number of virtual antennas
Return values
CFAR threshold in linear format
Definition at line 1972 of file mss_main.c.
References MMWDEMO_CFAR_THRESHOLD_ENCODING_FACTOR.
Referenced by MmwDemo_processPendingDynamicCfgCommands().
MmwDemo_dataPathConfig()
static int32_t MmwDemo_dataPathConfig (void) static
Description
The function is used to configure the data path based on the chirp profile. After this function is executed, the data path processing will ready to go when the ADC buffer starts receiving samples corresponding to the chirps.
Return values
Success - 0
Error - <0
Definition at line 2003 of file mss_main.c.
References DPIF_ADCBufProperty_t::adcBits, MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_RFParserOutParams_t::adcBufChanDataSize, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, DPC_ObjectDetectionRangeHWA_StaticCfg_t::ADCBufData, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_SubFrameCfg_t::bpmCfg, MmwDemo_MSS_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, MmwDemo_Cfg_t::ctrlCfg, DPIF_ADCBufData_t::data, DPIF_ADCBufProperty_t::dataFmt, DPIF_ADCBufData_t::dataProperty, MmwDemo_RFParserOutParams_t::dopplerStep, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPC_OBJDETRANGEHWA_IOCTL__STATIC_PRE_START_COMMON_CFG, DPM_ioctl(), MmwDemo_DPC_ObjDet_DynCfg_t::dspDynCfg, gMmwMssMCB, MmwDemo_SubFrameCfg_t::guiMonSel, MmwDemo_ADCBufCfg_t::iqSwapSel, MmwDemo_BpmCfg_t::isEnabled, MmwDemo_ADCBufConfig(), MmwDemo_configCQ(), MmwDemo_debugAssert, MmwDemo_DPM_ioctl_blocking(), MmwDemo_resetDynObjDetCommonCfgPendingState(), MmwDemo_RFParser_getNumSubFrames(), MmwDemo_RFParser_parseConfig(), MmwDemo_RFParserOutParams_t::numAdcSamples, MmwDemo_SubFrameCfg_t::numAdcSamples, MmwDemo_RFParserOutParams_t::numChirpsPerChirpEvent, MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, MmwDemo_RFParserOutParams_t::numChirpsPerFrame, MmwDemo_SubFrameCfg_t::numChirpsPerSubFrame, MmwDemo_RFParserOutParams_t::numDopplerBins, MmwDemo_SubFrameCfg_t::numDopplerBins, MmwDemo_RFParserOutParams_t::numDopplerChirps, MmwDemo_RFParserOutParams_t::numRangeBins, MmwDemo_SubFrameCfg_t::numRangeBins, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, DPC_ObjectDetectionRangeHWA_PreStartCommonCfg_t::numSubFrames, MmwDemo_RFParserOutParams_t::numVirtualAntennas, MmwDemo_SubFrameCfg_t::numVirtualAntennas, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_Cfg_t::openCfg, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_MSS_MCB_t::rfFreqScaleFactor, DPIF_ADCBufProperty_t::rxChanOffset, SOC_XWR68XX_MSS_ADCBUF_BASE_ADDRESS, MmwDemo_MSS_MCB_t::socHandle, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::staticCfg, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::subFrameNum, and MmwDemo_RFParserOutParams_t::validProfileIdx.
Referenced by MmwDemo_configSensor().
MmwDemo_dataPathOpen()
static void MmwDemo_dataPathOpen (void) static
Description
Perform Data path driver open
Return values
Not Applicable.
Definition at line 1835 of file mss_main.c.
References MmwDemo_MSS_MCB_t::adcBufHandle, gMmwMssMCB, MmwDemo_ADCBufOpen(), MmwDemo_debugAssert, and MmwDemo_MSS_MCB_t::socHandle.
Referenced by MmwDemo_openSensor().
MmwDemo_dataPathStart()
static void MmwDemo_dataPathStart (void) static
Description
This function is used to start data path to handle chirps from front end.
Return values
Not Applicable.
Definition at line 2333 of file mss_main.c.
References MmwDemo_LvdsStreamCfg_t::dataFmt, DPM_start(), MmwDemo_MSS_MCB_t::DPMstartSemHandle, gMmwMssMCB, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_DISABLED, MmwDemo_configLVDSHwData(), MmwDemo_debugAssert, MmwDemo_MSS_MCB_t::objDetDpmHandle, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_startSensor().
MmwDemo_dataPathStop()
static void MmwDemo_dataPathStop (void) static
Description
This function is used to stop data path.
Return values
Not Applicable.
Definition at line 2368 of file mss_main.c.
References DPM_stop(), gMmwMssMCB, MmwDemo_debugAssert, and MmwDemo_MSS_MCB_t::objDetDpmHandle.
Referenced by MmwDemo_eventCallbackFxn().
MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn()
static void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx) static
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of frame/sub-frame processing, we use this to issue BIOS calls for computing CPU load during inter-frame
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 3744 of file mss_main.c.
References gMmwMssMCB, MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_SubFrameStats_t::outputStats, and MmwDemo_MSS_MCB_t::subFrameStats.
Referenced by MmwDemo_initTask().
MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn()
static void MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn (uint8_t subFrameIndx) static
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of inter-frame/inter-sub-frame processing, we use this to issue BIOS calls for computing CPU load during active frame (chirping)
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 3762 of file mss_main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, gMmwMssMCB, MmwDemo_SubFrameStats_t::outputStats, and MmwDemo_MSS_MCB_t::subFrameStats.
Referenced by MmwDemo_initTask().
MmwDemo_DPC_ObjectDetection_reportFxn()
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1) static
Description
DPM Registered Report Handler. The DPM Module uses this registered function to notify the application about DPM reports.
Parameters
[in] reportType Report Type
[in] instanceId Instance Identifier which generated the report
[in] errCode Error code if any.
[in] arg0 Argument 0 interpreted with the report type
[in] arg1 Argument 1 interpreted with the report type
Return values
Not Applicable.
Definition at line 2520 of file mss_main.c.
References CLI_write(), DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL1RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL1RamUsage, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL2RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL2RamUsage, MmwDemo_MSS_MCB_t::dataPathObj, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPC_OBJDETRANGEHWA_IOCTL__STATIC_PRE_START_CFG, DPM_Report_DPC_ASSERT, DPM_Report_DPC_INFO, DPM_Report_DPC_STARTED, DPM_Report_DPC_STOPPED, DPM_Report_IOCTL, DPM_Report_NOTIFY_DPC_RESULT, DPM_Report_NOTIFY_DPC_RESULT_ACKED, MmwDemo_MSS_MCB_t::DPMioctlSemHandle, MmwDemo_MSS_Stats_t::dpmStartEvents, MmwDemo_MSS_MCB_t::DPMstartSemHandle, MmwDemo_MSS_Stats_t::dpmStopEvents, MmwDemo_MSS_MCB_t::DPMstopSemHandle, DPM_DPCAssert_t::fileName, gMmwMssMCB, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamUsage, DPM_DPCAssert_t::lineNum, DPC_ObjectDetection_PreStartCfg_t::memUsage, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::memUsage, MmwDemo_DataPathObj_t::memUsage, MmwDemo_handleObjectDetResult(), DPC_ObjectDetectionRangeHWA_PreStartCfg_t::radarCubeMem, MmwDemo_DataPathObj_t::radarCubeMem, MmwDemo_MSS_MCB_t::stats, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapUsed.
Referenced by MmwDemo_initTask().
MmwDemo_DPM_ioctl_blocking()
static int32_t MmwDemo_DPM_ioctl_blocking (DPM_Handle handle, uint32_t cmd, void * arg, uint32_t argLen) static
Description
Help function to make DPM_ioctl blocking until response is reported
Return values
Success -0 Failed <0
Definition at line 1717 of file mss_main.c.
References DPM_ioctl(), MmwDemo_MSS_MCB_t::DPMioctlSemHandle, and gMmwMssMCB.
Referenced by MmwDemo_dataPathConfig().
MmwDemo_EDMA_errorCallbackFxn()
static void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo) static
Description
Call back function for EDMA CC (Channel controller) error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 835 of file mss_main.c.
References MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_errorInfo, gMmwMssMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
MmwDemo_EDMA_transferControllerErrorCallbackFxn()
static void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo) static
Description
Call back function for EDMA transfer controller error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 848 of file mss_main.c.
References MmwDemo_MSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, gMmwMssMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
MmwDemo_edmaClose()
void MmwDemo_edmaClose (MmwDemo_DataPathObj * obj)
Description
Close EDMA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 908 of file mss_main.c.
References MmwDemo_DataPathObj_t::edmaHandle.
MmwDemo_edmaInit()
static void MmwDemo_edmaInit (MmwDemo_DataPathObj * obj, uint8_t instance) static
Description
EDMA driver init
Parameters
[in] obj Pointer to data path object
[in] instance EDMA instance
Return values
Not Applicable.
Definition at line 812 of file mss_main.c.
References MmwDemo_DataPathObj_t::EDMA_errorInfo, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
MmwDemo_edmaOpen()
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj * obj, uint8_t instance) static
Description
Open EDMA driver instance
Parameters
[in] obj Pointer to data path object
[in] instance EDMA instance
Return values
Not Applicable.
Definition at line 869 of file mss_main.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_debugAssert, MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Referenced by MmwDemo_initTask().
MmwDemo_eventCallbackFxn()
static int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload) static
Description
Registered event function to mmwave which is invoked when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always return 0
Definition at line 2400 of file mss_main.c.
References MmwDemo_MSS_Stats_t::calibrationReports, CLI_write(), MmwDemo_MSS_Stats_t::failedTimingReports, MmwDemo_MSS_Stats_t::frameTriggerReady, gMmwMssMCB, MmwDemo_dataPathStop(), MmwDemo_debugAssert, MmwDemo_MSS_Stats_t::sensorStopped, and MmwDemo_MSS_MCB_t::stats.
Referenced by MmwDemo_initTask().
MmwDemo_getNextSubFrameIndx()
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get next sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of next sub-frame.
Definition at line 2724 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult().
MmwDemo_getPrevSubFrameIndx()
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get previous sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of previous sub-frame
Definition at line 2750 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult().
MmwDemo_getTemperatureReport()
void MmwDemo_getTemperatureReport ()
Description
Utility function to get temperature report from front end and save it in global structure.
Return values
None
Definition at line 1310 of file mss_main.c.
References gMmwMssMCB, MmwDemo_temperatureStats_t::temperatureReport, MmwDemo_MSS_MCB_t::temperatureStats, and MmwDemo_temperatureStats_t::tempReportValid.
MmwDemo_handleObjectDetResult()
static void MmwDemo_handleObjectDetResult (DPM_Buffer * ptrResult) static
Description
Function to handle frame processing results from DPC
Parameters
[in] ptrResult Pointer to DPC result
Return values
Not Applicable.
Definition at line 3072 of file mss_main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_MSS_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, DPC_ObjectDetection_ExecuteResult_t::compRxChanBiasMeasurement, MmwDemo_LvdsStreamCfg_t::dataFmt, DPC_OBJDET_IOCTL__DYNAMIC_EXECUTE_RESULT_EXPORTED, DPM_ioctl(), DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, gMmwMssMCB, gts, gtsIdx, MmwDemo_LVDSStream_MCB::hwFrameDoneSemHandle, MmwDemo_output_message_stats_t::interChirpProcessingMargin, MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MmwDemo_MSS_MCB_t::loggingUartHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_DISABLED, MmwDemo_ADCBufConfig(), MmwDemo_configLVDSHwData(), MmwDemo_debugAssert, MmwDemo_getNextSubFrameIndx(), MmwDemo_getPrevSubFrameIndx(), MmwDemo_measurementResultOutput(), MmwDemo_processPendingDynamicCfgCommands(), MmwDemo_transferLVDSUserData(), MmwDemo_transmitProcessedOutput(), MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_Cfg_t::openCfg, MmwDemo_SubFrameStats_t::outputStats, MmwDemo_SubFrameStats_t::pendingConfigProcTime, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPM_Buffer_t::ptrBuffer, R4F_CLOCK_MHZ, DPM_Buffer_t::size, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, DPC_ObjectDetection_ExecuteResultExportedInfo_t::subFrameIdx, MmwDemo_SubFrameStats_t::subFramePreparationTime, MmwDemo_MSS_MCB_t::subFrameStats, MmwDemo_LVDSStream_MCB::swFrameDoneSemHandle, SYS_COMMON_NUM_RX_CHANNEL, and MmwDemo_output_message_stats_t::transmitOutputTime.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn().
MmwDemo_hwaClose()
void MmwDemo_hwaClose (MmwDemo_DataPathObj * obj)
Description
Close HWA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 964 of file mss_main.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
MmwDemo_hwaInit()
static void MmwDemo_hwaInit (MmwDemo_DataPathObj * obj) static
Description
HWA driver init
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 923 of file mss_main.c.
Referenced by MmwDemo_initTask().
MmwDemo_hwaOpen()
static void MmwDemo_hwaOpen (MmwDemo_DataPathObj * obj, SOC_Handle socHandle) static
Description
Open HWA driver instance
Parameters
[in] obj Pointer to data path object
[in] socHandle SOC driver handle
Return values
Not Applicable.
Definition at line 940 of file mss_main.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
MmwDemo_initTask()
static void MmwDemo_initTask (UArg arg0, UArg arg1) static
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 3995 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_MSS_MCB_t::commandUartHandle, MmwDemo_MSS_MCB_t::cqSatMonCfg, MmwDemo_MSS_MCB_t::cqSigImgMonCfg, MmwDemo_MSS_MCB_t::ctrlHandle, MmwDemo_MSS_MCB_t::dataPathObj, DPC_OBJDET_R4F_EDMA_INSTANCE, DPC_OBJDET_R4F_INSTANCEID, DPM_Domain_DISTRIBUTED, DPM_init(), DPM_synch(), MmwDemo_MSS_MCB_t::DPMioctlSemHandle, MmwDemo_MSS_MCB_t::DPMstartSemHandle, MmwDemo_MSS_MCB_t::DPMstopSemHandle, MmwDemo_DataPathObj_t::edmaHandle, gDPC_ObjDetRangeHWACfg, gDPCTCM, gMmwL3, gMmwMssMCB, MmwDemo_DataPathObj_t::hwaHandle, MmwDemo_platformCfg_t::loggingBaudRate, MmwDemo_MSS_MCB_t::loggingUartHandle, MMWave_ConfigurationMode_FULL, MMWave_Domain_MSS, MMWave_ExecutionMode_ISOLATION, MMWave_init(), MMWave_sync(), MmwDemo_TaskHandles_t::mmwaveCtrl, MmwDemo_calibInit(), MMWDEMO_CLI_TASK_PRIORITY, MmwDemo_CLIInit(), MmwDemo_debugAssert, MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY, MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_edmaInit(), MmwDemo_edmaOpen(), MmwDemo_eventCallbackFxn(), MmwDemo_hwaInit(), MmwDemo_hwaOpen(), MmwDemo_LVDSStreamInit(), MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY, MmwDemo_mmWaveCtrlTask(), mmwDemo_mssDPMTask(), MmwDemo_platformInit(), MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_TaskHandles_t::objDetDpmTask, MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::socHandle, MmwDemo_platformCfg_t::sysClockFrequency, and MmwDemo_MSS_MCB_t::taskHandles.
Referenced by main().
MmwDemo_isAllCfgInNonPendingState()
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in non-pending (cleared) state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in non-pending state, else return 0
Definition at line 1248 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, MmwDemo_isDynObjDetCfgInNonPendingState(), MmwDemo_isDynObjDetCommonCfgInNonPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_isAllCfgInPendingState()
uint8_t MmwDemo_isAllCfgInPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in pending state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in pending state, else return 0
Definition at line 1222 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, MmwDemo_isDynObjDetCfgPendingState(), MmwDemo_isDynObjDetCommonCfgPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_isDynObjDetCfgInNonPendingState()
static uint8_t MmwDemo_isDynObjDetCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all sub-frame specific dynamic configuration is in non-pending state, else return 0
Definition at line 1134 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isExtMaxVelCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
MmwDemo_isDynObjDetCfgPendingState()
static uint8_t MmwDemo_isDynObjDetCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is pending
Parameters
[in] cfg Pointer to sub-frame specific configuration
Return values
1 if all sub-frame specific dynamic configuration is pending, else return 0
Definition at line 1085 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isExtMaxVelCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
MmwDemo_isDynObjDetCommonCfgInNonPendingState()
static uint8_t MmwDemo_isDynObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all dynamic common configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all common configuration is in non-pending state, else return 0
Definition at line 1113 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
MmwDemo_isDynObjDetCommonCfgPendingState()
static uint8_t MmwDemo_isDynObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all dynamic common configuration is pending
Parameters
[in] cfg Pointer to Common configuration
Return values
1 if all common configuration is pending, else return 0.
Definition at line 1064 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
MmwDemo_measurementResultOutput()
static void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg * compRxChanCfg) static
Definition at line 1322 of file mss_main.c.
References CLI_write(), cmplx16ImRe_t_::imag, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, cmplx16ImRe_t_::real, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, and SYS_COMMON_NUM_TX_ANTENNAS.
Referenced by MmwDemo_handleObjectDetResult().
MmwDemo_mmWaveCtrlStop()
static int32_t MmwDemo_mmWaveCtrlStop (void) static
Description
The function is used to trigger the Front end to stop generating chirps.
Return values
Not Applicable.
Definition at line 1645 of file mss_main.c.
References MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MMWave_decodeError(), MMWave_ErrorLevel_ERROR, MMWave_stop(), and MmwDemo_debugAssert.
Referenced by MmwDemo_stopSensor().
MmwDemo_mmWaveCtrlTask()
static void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1) static
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 1689 of file mss_main.c.
References MmwDemo_MSS_MCB_t::ctrlHandle, gMmwMssMCB, MMWave_execute(), and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
mmwDemo_mssDPMTask()
static void mmwDemo_mssDPMTask (UArg arg0, UArg arg1) static
Description
DPM Execution Task which executes the DPM Instance which manages the HL Profiles executing on the MSS.
Return values
Not Applicable.
Definition at line 3285 of file mss_main.c.
References DPM_execute(), gMmwMssMCB, and MmwDemo_MSS_MCB_t::objDetDpmHandle.
Referenced by MmwDemo_initTask().
MmwDemo_mssSetHsiClk()
int32_t MmwDemo_mssSetHsiClk (void)
Description
Function to Setup the HSI Clock. Required for LVDS streaming.
Return values
0 - Success. <0 - Failed with errors
Definition at line 3310 of file mss_main.c.
References HSI_DCA_MIN_DELAY_MSEC.
Referenced by MmwDemo_openSensor().
MmwDemo_openSensor()
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
Description
mmw demo helper Function to do one time sensor initialization. User need to fill gMmwMssMCB.cfg.openCfg before calling this function
Parameters
[in] isFirstTimeOpen If true then issues MMwave_open
Return values
Success - 0
Error - <0
Definition at line 3358 of file mss_main.c.
References MmwDemo_MSS_MCB_t::calibCfg, MmwDemo_calibData_t::calibData, MmwDemo_calibCfg_t::calibDataHdr, MMWave_OpenCfg_t::calibMonTimeUnit, MmwDemo_MSS_MCB_t::cfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_OpenCfg_t::customCalibrationEnableMask, MMWave_OpenCfg_t::disableFrameStartAsyncEvent, MMWave_OpenCfg_t::disableFrameStopAsyncEvent, MMWave_OpenCfg_t::freqLimitHigh, MMWave_OpenCfg_t::freqLimitLow, gCalibDataStorage, gMmwMssMCB, gRFLdoBypassCfg, MMWave_decodeError(), MMWave_open(), MmwDemo_calibRestore(), MmwDemo_calibSave(), MmwDemo_dataPathOpen(), MmwDemo_mssSetHsiClk(), MmwDemo_Cfg_t::openCfg, MmwDemo_calibData_t::phaseShiftCalibData, MMWave_CalibrationData_t::ptrCalibData, MMWave_CalibrationData_t::ptrPhaseShiftCalibData, MmwDemo_calibCfg_t::restoreEnable, MmwDemo_calibCfg_t::saveEnable, and MMWave_OpenCfg_t::useCustomCalibration.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_platformInit()
static void MmwDemo_platformInit (MmwDemo_platformCfg * config) static
Description
Platform specific hardware initialization.
Parameters
[in] config Platform initialization configuraiton
Return values
Not Applicable.
Definition at line 3782 of file mss_main.c.
References MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_platformCfg_t::loggingBaudRate, MSS_SYS_VCLK, MmwDemo_platformCfg_t::SensorStatusGPIO, SOC_XWR68XX_GPIO_2, and MmwDemo_platformCfg_t::sysClockFrequency.
Referenced by MmwDemo_initTask().
MmwDemo_processPendingDynamicCfgCommands()
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx) static
Description
Processes any pending dynamic configuration commands for the specified sub-frame by fanning out to the respective DPUs using IOCTL interface, and resets (clears) the pending state after processing.
Parameters
[in] subFrameIndx Sub-frame index of desired sub-frame to process
Return values
Success - 0
Error - <0
Definition at line 2779 of file mss_main.c.
References DPC_ObjectDetectionRangeHWA_DynCfg_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPC_ObjectDetection_fovDopplerCfg_t::cfg, DPC_ObjectDetection_fovRangeCfg_t::cfg, DPC_ObjectDetection_extMaxVelCfg_t::cfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::cfg, DPC_ObjectDetection_CfarCfg_t::cfg, DPC_ObjectDetection_StaticClutterRemovalCfg_t::cfg, DPC_ObjectDetection_fovAoaCfg_t::cfg, DPC_ObjectDetectionRangeHWA_CalibDcRangeSigCfg_t::cfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_DOPPLER_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_RANGE_CFG, DPC_OBJDET_IOCTL__DYNAMIC_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_EXT_MAX_VELOCITY, DPC_OBJDET_IOCTL__DYNAMIC_FOV_AOA, DPC_OBJDET_IOCTL__DYNAMIC_FOV_DOPPLER, DPC_OBJDET_IOCTL__DYNAMIC_FOV_RANGE, DPC_OBJDET_IOCTL__DYNAMIC_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_MULTI_OBJ_BEAM_FORM_CFG, DPC_OBJDET_IOCTL__DYNAMIC_RANGE_AZIMUTH_HEAT_MAP, DPC_OBJDET_IOCTL__DYNAMIC_STATICCLUTTER_REMOVAL_CFG, DPC_OBJDETRANGEHWA_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPM_ioctl(), MmwDemo_DPC_ObjDet_DynCfg_t::dspDynCfg, DPC_ObjectDetection_DynCfg_t::extMaxVelCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovRange, gMmwMssMCB, MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isExtMaxVelCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MmwDemo_convertCfarToLinear(), DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, MmwDemo_SubFrameCfg_t::numVirtualAntennas, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_DPC_ObjDet_DynCfg_t::r4fDynCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::subFrameNum, DPC_ObjectDetection_StaticClutterRemovalCfg_t::subFrameNum, DPC_ObjectDetection_CfarCfg_t::subFrameNum, DPC_ObjectDetection_fovAoaCfg_t::subFrameNum, DPC_ObjectDetection_fovDopplerCfg_t::subFrameNum, DPC_ObjectDetection_extMaxVelCfg_t::subFrameNum, DPC_ObjectDetection_fovRangeCfg_t::subFrameNum, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::subFrameNum, DPC_ObjectDetectionRangeHWA_CalibDcRangeSigCfg_t::subFrameNum, and DPU_CFARCAProc_CfarCfg_t::thresholdScale.
Referenced by MmwDemo_handleObjectDetResult().
MmwDemo_resetDynObjDetCfgPendingState()
static void MmwDemo_resetDynObjDetCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Resets (clears) all pending sub-frame specific dynamic configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC sub-frame dynamic configuration
Return values
Not Applicable.
Definition at line 1179 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isExtMaxVelCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
MmwDemo_resetDynObjDetCommonCfgPendingState()
static void MmwDemo_resetDynObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Resets (clears) all pending dynamic common configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC common configuration
Return values
Not Applicable.
Definition at line 1162 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_dataPathConfig().
MmwDemo_resetStaticCfgPendingState()
void MmwDemo_resetStaticCfgPendingState (void)
Description
Resets (clears) all pending static (non-dynamic) configuration
Definition at line 1199 of file mss_main.c.
References gMmwMssMCB, MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_MSS_MCB_t::isAnaMonCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStop().
MmwDemo_sensorStopEpilog()
static void MmwDemo_sensorStopEpilog (void) static
Description
Epilog processing after sensor has stopped
Return values
None
Definition at line 3619 of file mss_main.c.
References gMmwMssMCB, MmwDemo_TaskHandles_t::initTask, MmwDemo_TaskHandles_t::mmwaveCtrl, MmwDemo_debugAssert, MmwDemo_TaskHandles_t::objDetDpmTask, and MmwDemo_MSS_MCB_t::taskHandles.
Referenced by MmwDemo_stopSensor().
MmwDemo_setSubFramePendingState()
static void MmwDemo_setSubFramePendingState (MmwDemo_SubFrameCfg * subFrameCfg, uint32_t offset) static
Description
Utility function to set the pending state of configuration.
Parameters
[in] subFrameCfg Pointer to Sub-frame specific configuration
[in] offset Configuration structure offset that uniquely identifies the configuration to set to the pending state.
Return values
None
Definition at line 1005 of file mss_main.c.
References MmwDemo_SubFrameCfg_t::isAdcBufCfgPending, MmwDemo_SubFrameCfg_t::isBpmCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isExtMaxVelCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_SubFrameCfg_t::isLvdsStreamCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, MMWDEMO_ADCBUFCFG_OFFSET, MMWDEMO_BPMCFG_OFFSET, MMWDEMO_CALIBDCRANGESIG_OFFSET, MMWDEMO_CFARCFGDOPPLER_OFFSET, MMWDEMO_CFARCFGRANGE_OFFSET, MmwDemo_debugAssert, MMWDEMO_EXTMAXVEL_OFFSET, MMWDEMO_FOVAOA_OFFSET, MMWDEMO_FOVDOPPLER_OFFSET, MMWDEMO_FOVRANGE_OFFSET, MMWDEMO_GUIMONSEL_OFFSET, MMWDEMO_LVDSSTREAMCFG_OFFSET, MMWDEMO_MULTIOBJBEAMFORMING_OFFSET, MMWDEMO_STATICCLUTTERREMOFVAL_OFFSET, and MmwDemo_SubFrameCfg_t::objDetDynCfg.
Referenced by MmwDemo_CfgUpdate().
MmwDemo_sleep()
void MmwDemo_sleep (void)
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 4240 of file mss_main.c.
MmwDemo_startSensor()
int32_t MmwDemo_startSensor (void)
Description
mmw demo helper Function to start sensor.
Return values
Success - 0
Error - <0
Definition at line 3560 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_CtrlCfg_t::dfeDataOutputMode, gMmwMssMCB, gts, gtsIdx, MMWave_decodeError(), MMWave_start(), MmwDemo_dataPathStart(), MmwDemo_debugAssert, MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::sensorStartCount, and MmwDemo_platformCfg_t::SensorStatusGPIO.
Referenced by MmwDemo_CLISensorStart().
MmwDemo_stopSensor()
void MmwDemo_stopSensor (void)
Description
Stops the RF and datapath for the sensor. Blocks until both operation are completed. Prints epilog at the end.
Return values
None
Definition at line 3672 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_MSS_MCB_t::DPMstopSemHandle, gMmwMssMCB, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_SubFrameCfg_t::lvdsStreamCfg, MMW_DEMO_LVDS_STREAM_CFG_DATAFMT_DISABLED, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteHwSession(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_mmWaveCtrlStop(), MmwDemo_sensorStopEpilog(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_Cfg_t::platformCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_MSS_MCB_t::sensorStartCount, MmwDemo_platformCfg_t::SensorStatusGPIO, MmwDemo_MSS_MCB_t::sensorStopCount, MmwDemo_MSS_MCB_t::subFrameCfg, and MmwDemo_LVDSStream_MCB::swSessionHandle.
Referenced by MmwDemo_CLISensorStop().
MmwDemo_transferLVDSUserData()
void MmwDemo_transferLVDSUserData (uint8_t subFrameIndx, DPC_ObjectDetection_ExecuteResult * dpcResults)
Description
Transmit user data over LVDS interface.
Parameters
[in] subFrameIndx Sub-frame index
[in] dpcResults pointer to DPC result
Definition at line 3001 of file mss_main.c.
References MmwDemo_LVDSUserDataHeader::detObjNum, MmwDemo_LVDSUserDataHeader::frameNum, DPC_ObjectDetection_Stats_t::frameStartIntCounter, gMmwMssMCB, MmwDemo_MSS_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_LVDSStreamSwConfig(), DPC_ObjectDetection_ExecuteResult_t::numObjOut, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, DPC_ObjectDetection_ExecuteResult_t::stats, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, MmwDemo_LVDSUserDataHeader::subFrameNum, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_handleObjectDetResult().
MmwDemo_transmitProcessedOutput()
static void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult * result, MmwDemo_output_message_stats * timingInfo) static
Transmits detection data over UART.
The following data is transmitted:
Header (size = 32bytes), including "Magic word", (size = 8 bytes) and including the number of TLV items TLV Items:
If detectedObjects flag is 1 or 2, DPIF_PointCloudCartesian structure containing X,Y,Z location and velocity for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If detectedObjects flag is 1, DPIF_PointCloudSideInfo structure containing SNR and noise for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If logMagRange flag is set, rangeProfile, size = number of range bins * sizeof(uint16_t)
If noiseProfile flag is set, noiseProfile, size = number of range bins * sizeof(uint16_t)
If rangeAzimuthHeatMap flag is set, the zero Doppler column of the range cubed matrix, size = number of Rx Azimuth virtual antennas * number of chirps per frame * sizeof(uint32_t)
If rangeDopplerHeatMap flag is set, the log magnitude range-Doppler matrix, size = number of range bins * number of Doppler bins * sizeof(uint16_t)
If statsInfo flag is set, the stats information
Parameters
[in] uartHandle UART driver handle
[in] result Pointer to result from object detection DPC processing
[in] timingInfo Pointer to timing information provided from core that runs data path
Definition at line 1362 of file mss_main.c.
References DPIF_DetMatrix_t::data, DPIF_RadarCube_t::data, MmwDemo_GuiMonSel_t::detectedObjects, DPC_ObjectDetection_ExecuteResult_t::detMatrix, gMmwMssMCB, MmwDemo_SubFrameCfg_t::guiMonSel, MmwDemo_output_message_tl_t::length, MmwDemo_output_message_header_t::magicWord, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS, MMWDEMO_OUTPUT_MSG_MAX, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MmwDemo_output_message_header_t::numDetectedObj, DPC_ObjectDetection_ExecuteResult_t::numObjOut, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, MmwDemo_output_message_header_t::platform, DPC_ObjectDetection_ExecuteResult_t::radarCube, DPC_ObjectDetection_ExecuteResult_t::stats, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, MmwDemo_output_message_tl_t::type, and MmwDemo_output_message_header_t::version.
Referenced by MmwDemo_handleObjectDetResult().
Variable Documentation
gCalibDataStorage
MmwDemo_calibData gCalibDataStorage
Definition at line 722 of file mss_main.c.
Referenced by MmwDemo_calibInit(), and MmwDemo_openSensor().
gDPCTCM
uint8_t gDPCTCM[MMWDEMO_OBJDET_LOCALRAM_SIZE]
Definition at line 698 of file mss_main.c.
Referenced by MmwDemo_initTask().
gHSRAM
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
Definition at line 690 of file mss_main.c.
gMmwL3
uint8_t gMmwL3[SOC_L3RAM_SIZE]
L3 RAM buffer for object detection DPC
Definition at line 703 of file mss_main.c.
Referenced by MmwDemo_initTask().
gMmwMssMCB
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 684 of file mss_main.c.
Referenced by main(), MmwDemo_bpmConfig(), MmwDemo_calibInit(), MmwDemo_calibRestore(), MmwDemo_calibSave(), MmwDemo_CfgUpdate(), MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDataSaveRestore(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIConfigDataPort(), MmwDemo_CLIInit(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIQueryDemoStatus(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), MmwDemo_configCQ(), MmwDemo_configLVDSHwData(), MmwDemo_configSensor(), MmwDemo_dataPathConfig(), MmwDemo_dataPathOpen(), MmwDemo_dataPathStart(), MmwDemo_dataPathStop(), MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_processInterFrameCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_DPM_ioctl_blocking(), MmwDemo_EDMA_errorCallbackFxn(), MmwDemo_EDMA_transferControllerErrorCallbackFxn(), MmwDemo_eventCallbackFxn(), MmwDemo_getTemperatureReport(), MmwDemo_handleObjectDetResult(), MmwDemo_initTask(), MmwDemo_isAllCfgInNonPendingState(), MmwDemo_isAllCfgInPendingState(), MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAInit(), MmwDemo_LVDSStream_HwTriggerFrameDone(), MmwDemo_LVDSStream_SwTriggerFrameDone(), MmwDemo_LVDSStreamDeleteHwSession(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_LVDSStreamHwConfig(), MmwDemo_LVDSStreamInit(), MmwDemo_LVDSStreamSwConfig(), MmwDemo_mmWaveCtrlStop(), MmwDemo_mmWaveCtrlTask(), mmwDemo_mssDPMTask(), MmwDemo_openSensor(), MmwDemo_processPendingDynamicCfgCommands(), MmwDemo_resetStaticCfgPendingState(), MmwDemo_sensorStopEpilog(), MmwDemo_startSensor(), MmwDemo_stopSensor(), MmwDemo_transferLVDSUserData(), and MmwDemo_transmitProcessedOutput().
gRFLdoBypassCfg
rlRfLdoBypassCfg_t gRFLdoBypassCfg
Initial value:
=
{
    .ldoBypassEnable   = 0,
    .supplyMonIrDrop   = 0,
    .ioSupplyIndicator = 0,
}
Global Variable for LDO BYPASS config, PLease consult your board/EVM user guide before changing the values here.
Definition at line 712 of file mss_main.c.
Referenced by MmwDemo_openSensor().
gts
uint32_t gts[100]
Definition at line 3059 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult(), and MmwDemo_startSensor().
gtsIdx
uint32_t gtsIdx = 0
Definition at line 3060 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult(), and MmwDemo_startSensor().
Copyright 2024, Texas Instruments Incorporated